export const posts = [
    {
      id:1,
      title:"Wyszukiwanie binarne",
      source:"post_2_wyszukiwanie_binarne.js", 
      description:"Dowiesz sie czym jest algorytm wyszukiwania binarnego i jak go zakodować w pythonie.", 
      slug:"wyszukiwanie-binarne", 
      tags:[
          "algorytmy", 
          "programowanie", 
          "python"
        ]
    },
    {  
      id:2,
      title:"Kości z Catanu", 
      source:"kosci_z_catanu.js", 
      description:"Dlaczego w grze planszowej Catan warto ustawiać się przy polach 6 i 8 ?", 
      slug:"kosci-z-catanu", 
      tags:[
          "statystyka", 
          "programowanie", 
          "python"
        ]
    },
]

export const projects = [
  {
    id: 7, 
    title: 'Wordy - ucz się czego chcesz', 
    subtitle: "Aplikacja internetowa",
    github: '', 
    page: '', 
    description: 'Aplikacja do nauki słówek w której nauka jest wspomagana przez Reinforcement Learning. Jest możliwosć nauki dla dzieci od 2-6 lat oraz wybor gier które rozwijają człowieka poznawczo.', 
    data: '01.12.2020', 
    techstack: [
        { id: 1, name: 'react' },
        { id: 2, name: 'django'},
        { id: 3, name: 'HTML' },
        { id: 1, name: 'CSS' }, 
    ],
  },
  {
    id: 6, 
    image:"licencjat.png", 
    source:"licencjat.js",  
    slug: 'licencjat', 
    type:'RESEARCH', 
    title: 'Licencjat', 
    github: '', 
    page: require('assets/posts/licencjat.pdf'), 
    description: "Wraz z promotorem przeprowadziliśmy eksperyment, w którym porównaliśmy trzy metody aktywacji przycisków za pomocy spojrzenia (metoda wykorzystująca czas spojrzenia, wykorzystująca wykrywanie fiksacji oraz gesty wzrokowe) oraz dwa układy klawiatury numerycznej. Przebadaliśmy zdrowe osoby, z których każda wprowadzała czterocyfrowe numery PIN w każdym z sześciu warunków eksperymentu. Okazało się, że najgorzej wypadła metoda wykorzystująca gesty wzrokowe. Eksperyment pozwolił jednak na ustalenie problemów związanych z jej użyciem, które pomogą w dalszym jej rozwoju.", 
    data: '01.12.2020', 
    techstack: [
        { id: 1, name: 'r' }
    ],
  },
  {
    id: 8,
    image:"neuromania.png", 
    source:"",  
    slug: '',  
    type:'PAGE', 
    title: 'Neuromania', 
    subtitle: "Strona internetowa",
    github: '', 
    page: 'https://neuromania-conference.netlify.app/', 
    description: "Stronę stworzyłem dla konferencji orgranizowanej przez koło naukowe kognitywistów z Torunia. Pomagam w tworzeniu tej konferencji od poprzedniej edycji i jest to nowa odsłona strony, która mam nadzieje zostanie już na dłużej i wraz kołem będziemy ją dalej rozwijać np. poprzez dodanie do niej systemu konferencyjnego, który będzie pozwalał na obsługę recenzji i płatności. Projekt wpierw został zaprojektowany w figmie, później zaprogramowałem stronę za pomocą Gatsby.", 
    data: '', 
    techstack: [
        { id: 1, name: 'react' }, 
        { id: 2, name: 'gatsby' }, 
        { id: 3, name: 'css' }, 
        { id: 4, name: 'js' }],
  },
  {
    id: 8,
    image:"fizjoterapia.png", 
    source:"neurotechtor.js",  
    slug: '',  
    type:'PAGE', 
    title: 'Fizjoterapia', 
    subtitle: "Strona internetowa",
    github: '', 
    page: 'https://ks-fizjo.netlify.app/', 
    description: "Strona wizytkówka/oferta dla fizjoterapeutki. Strona została zaprojektowana przy współpracy UI designerem w figmie, natomiast kod strony zaprogramowałem za pomocą Gatsby.", 
    data: '', 
    techstack: [
        { id: 1, name: 'react' }, 
        { id: 2, name: 'gatsby' }, 
        { id: 3, name: 'css' }, 
        { id: 4, name: 'js' }],
  },
  {
    id: 1,
    image:"neurotechtor.png", 
    source:"neurotechtor.js",  
    slug: '',  
    type:'PAGE', 
    title: 'Neurotechtor', 
    subtitle: "Strona internetowa",
    github: '', 
    page: 'https://neurotechtor.netlify.app/', 
    description: "Strone stworzyłem dla koła naukowego działającego na uniwersytecie Mikołaja Kopernika w Toruniu. Stworzyłem projekt w figmie wraz UX designerem i zaprogramowałem stronę w Gatsby.", 
    data: '', 
    techstack: [
        { id: 1, name: 'react' }, 
        { id: 2, name: 'gatsby' }, 
        { id: 3, name: 'css' }, 
        { id: 4, name: 'js' }],
  },
  {
    id: 1,
    image:"neurodio.png", 
    source:"staz_neurodio.js",  
    slug: 'staz-neurodio',  
    type:'PAGE', 
    title: 'Staż Neurodio', 
    subtitle: "Aplikacja internetowa",
    github: '', 
    page: 'http://neurodio.com/en/download-our-games/', 
    description: "Staż zdobyłem w ramach konkursu organizowanego przez UMK i trwał on jeden miesiąc. W ramach stażu stworzyłem frontend za pomocą React'a podłączonego do wcześniej stworzonego REST Api w ASP.Net Core. Oprócz trenowania wcześniejszych umiejętności podczas tworzenia tej strony nauczyłem się dwóch kolejnych bibliotek: React Query i React Formik oraz rozwinąłem swoje umiejętności w tworzeniu własnych hooków. Pracowalimy przy tym projekcie zdalnie w grupie czterech osób.", 
    data: '', 
    techstack: [
        { id: 1, name: 'react' }, 
        { id: 2, name: 'html' }, 
        { id: 3, name: 'css' }, 
        { id: 4, name: 'js' }],
  },
  {
    id: 2, 
    image:"guesswho.png", 
    source:"guess_who.js",  
    slug: 'guess-who', 
    type:'PAGE', 
    title: 'GuessWho', 
    subtitle: "Aplikacja internetowa",
    github: 'https://github.com/Snikerso/ml-django-react-frontend', 
    page: 'https://guess-whoo.netlify.app/', 
    description: 'Celem tego projektu było nauczenie się łączenia frontendu z obliczeniami Machine Learning po stronie backendu. Aplikacja polega na wrzuceniu 7 zdjęć po stronie frontendu i przeliczeniu podobieństwa przez regresje liniową, tak żeby stworzyć najlepszą podobiznę zdjęcia targetowego - taki Regression Fake.', 
    data: '', 
    techstack:  [
        { id: 1, name: 'react' }, 
        { id: 2, name: 'django' }, 
        { id: 3, name: 'html' }, 
        { id: 4, name: 'css' },
        { id: 5, name:'python',},
    ],
  },
  {
    id: 3,
    image:"umbridge_diary.png", 
    source:"umbridges_diary.js",  
    slug: 'umbridges-diary', 
    type:'PAGE', 
    title: 'Ubridge’s Diary',
    subtitle: "Aplikacja internetowa", 
    github: 'https://github.com/Snikerso/umbridge-diary-frontend', 
    page: 'https://umbridge-diary.netlify.app/', 
    description: 'Jest to aplikacja internetowa, którą zrobiłem dla treningu i do portfolio. Nauczyłem się przy niej tworzyć Rest Api w Django oraz rozwinąłem swoje umiejętności w React.js m.in.: w zarządzaniu stanem za pomocą hooków useReducer i useContect, tworzeniu systemu logowania oraz Styled Components.', 
    data: '', 
    techstack: [
        {id: 1, name:'react'},
        {id: 2, name:'django'},
        {id: 3, name:'css'},
        {id: 4, name:'html'},
        {id: 5, name:'python'},],
  },
  {
    id: 5,
    image:"umk.png", 
    source:"kognitywistyka_umk.js",
    slug: 'kognitywistyka-umk', 
    type:'PAGE', 
    title: 'Kognitywistyka UMK', 
    subtitle: "Strona internetowa", 
    github: '', 
    page: 'https://kognitywistyka.umk.pl/', 
    description: 'Celem tego komercyjnego projektu było poprawienie strony internetowej od strony wizualnej. Strona została zbudowana w WordPress. Aktualnie poprawiam SEO oraz wrzucam aktualności na stroną.', 
    techstack: [
        { id: 1, name: 'html' }, 
        { id: 2, name: 'css' }],
  },
];